// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIG.Infrastructure.Persistence;

#nullable disable

namespace SIG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623150000_AddPaymentModelsConfiguration")]
    partial class AddPaymentModelsConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIG.Domain.Entities.ConceptValidationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AggregationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregation_level");

                    b.Property<string>("CalculationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("calculation_method");

                    b.Property<int>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsApplicable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_applicable");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<string>("PaymentModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_model_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_concept_validation_rules");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_concept_validation_rules_concept_id");

                    b.HasIndex("ConceptId", "PaymentModelType")
                        .HasDatabaseName("ix_concept_validation_rules_concept_payment_model");

                    b.ToTable("concept_validation_rules", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.EmployeePaymentModelMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("effective_until");

                    b.Property<int>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("PaymentModelId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_model_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee_payment_model_mappings");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_employee_payment_model_mappings_client_id");

                    b.HasIndex("EmployeeCode")
                        .HasDatabaseName("ix_employee_payment_model_mappings_employee_code");

                    b.HasIndex("PaymentModelId")
                        .HasDatabaseName("ix_employee_payment_model_mappings_payment_model_id");

                    b.ToTable("employee_payment_model_mappings", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.PaymentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("effective_until");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payment_models");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payment_models_client_id");

                    b.HasIndex("ClientId", "ModelType")
                        .HasDatabaseName("ix_payment_models_client_id_model_type");

                    b.ToTable("payment_models", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.PaymentRatesConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("base_rate");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<int?>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("min_value");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("RateFormula")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rate_formula");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rate_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_payment_rates_configuration");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_payment_rates_configuration_client_id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_payment_rates_configuration_concept_id");

                    b.HasIndex("ClientId", "Year", "Month")
                        .HasDatabaseName("ix_payment_rates_configuration_client_year_month");

                    b.ToTable("payment_rates_configuration", (string)null);
                });

            // Configure relationships and other entities...
#pragma warning restore 612, 618
        }
    }
}
