// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIG.Infrastructure.Persistence;

#nullable disable

namespace SIG.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525201721_BiSchemaViews")]
    partial class BiSchemaViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIG.Domain.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_actions");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_actions_client_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_actions_department_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_actions_project_id");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ActionConcept", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    b.Property<int>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.HasKey("ActionId", "ConceptId")
                        .HasName("pk_action_concepts");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_action_concepts_concept_id");

                    b.ToTable("action_concepts", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ActionUser", b =>
                {
                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ActionId", "UserId")
                        .HasName("pk_action_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_action_users_user_id");

                    b.ToTable("action_users", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosureId")
                        .HasColumnType("integer")
                        .HasColumnName("closure_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_decision");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motivo");

                    b.Property<int>("Paso")
                        .HasColumnType("integer")
                        .HasColumnName("paso");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("ClosureId")
                        .HasDatabaseName("ix_approvals_closure_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_approvals_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_approvals_user_id");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<int>("ClosureId")
                        .HasColumnType("integer")
                        .HasColumnName("closure_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("motivo");

                    b.Property<int>("PasoDestino")
                        .HasColumnType("integer")
                        .HasColumnName("paso_destino");

                    b.Property<int>("PasoOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("paso_origen");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_approval_history");

                    b.HasIndex("ClosureId")
                        .HasDatabaseName("ix_approval_history_closure_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_approval_history_user_id");

                    b.ToTable("approval_history", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value_json");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value_json");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.CalculationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosureLineId")
                        .HasColumnType("integer")
                        .HasColumnName("closure_line_id");

                    b.Property<int>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<string>("FormulaSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("formula_snapshot_json");

                    b.Property<string>("Incidencias")
                        .HasColumnType("jsonb")
                        .HasColumnName("incidencias");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inputs_json");

                    b.Property<decimal>("Resultado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("resultado");

                    b.Property<string>("SistemaOrigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sistema_origen");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_calculation_logs");

                    b.HasIndex("ClosureLineId")
                        .IsUnique()
                        .HasDatabaseName("ix_calculation_logs_closure_line_id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_calculation_logs_concept_id");

                    b.ToTable("calculation_logs", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("ContactoEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contacto_email");

                    b.Property<string>("ContactoNombre")
                        .HasColumnType("text")
                        .HasColumnName("contacto_nombre");

                    b.Property<string>("ContactoTelefono")
                        .HasColumnType("text")
                        .HasColumnName("contacto_telefono");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provincia");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Closure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentarios");

                    b.Property<decimal>("CosteTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("coste_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<decimal>("FacturacionTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("facturacion_total");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal>("Margen")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("margen");

                    b.Property<int>("PasoActual")
                        .HasColumnType("integer")
                        .HasColumnName("paso_actual");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_closures");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_closures_period_id");

                    b.HasIndex("ProjectId", "PeriodId")
                        .IsUnique()
                        .HasDatabaseName("ix_closures_project_id_period_id");

                    b.ToTable("closures", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ClosureLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosureId")
                        .HasColumnType("integer")
                        .HasColumnName("closure_id");

                    b.Property<int>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatosEntradaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_entrada_json");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("importe");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<bool>("TieneIncidencia")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_incidencia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_closure_lines");

                    b.HasIndex("ClosureId")
                        .HasDatabaseName("ix_closure_lines_closure_id");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_closure_lines_concept_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_closure_lines_user_id");

                    b.ToTable("closure_lines", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desde");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_hasta");

                    b.Property<string>("FormulaJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("formula_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_concepts");

                    b.ToTable("concepts", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ConceptUser", b =>
                {
                    b.Property<int>("ConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("concept_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ConceptId", "UserId")
                        .HasName("pk_concept_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_concept_users_user_id");

                    b.ToTable("concept_users", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cost_centers");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_centers_codigo");

                    b.ToTable("cost_centers", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_nombre");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date")
                        .HasColumnName("fecha_alta");

                    b.Property<string>("InterlocutorEmail")
                        .HasColumnType("text")
                        .HasColumnName("interlocutor_email");

                    b.Property<string>("InterlocutorNombre")
                        .HasColumnType("text")
                        .HasColumnName("interlocutor_nombre");

                    b.Property<string>("InterlocutorTelefono")
                        .HasColumnType("text")
                        .HasColumnName("interlocutor_telefono");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_projects_client_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ProjectCostCenter", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("cost_center_id");

                    b.HasKey("ProjectId", "CostCenterId")
                        .HasName("pk_project_cost_centers");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_project_cost_centers_cost_center_id");

                    b.ToTable("project_cost_centers", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.ProjectUser", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_users_user_id");

                    b.ToTable("project_users", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Staging.StagingBizneoEmpleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("EmpleadoIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empleado_id_externo");

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_sincronizacion");

                    b.Property<bool>("FlagProcesado")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_procesado");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staging_bizneo_empleados");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_staging_bizneo_empleados_hash");

                    b.ToTable("staging_bizneo_empleados", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Staging.StagingBizneoHora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_sincronizacion");

                    b.Property<bool>("FlagProcesado")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_procesado");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<decimal>("Horas")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("horas");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("RegistroIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("registro_id_externo");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staging_bizneo_horas");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_staging_bizneo_horas_hash");

                    b.ToTable("staging_bizneo_horas", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Staging.StagingCeleroVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_sincronizacion");

                    b.Property<bool>("FlagProcesado")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_procesado");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("PuntoMontado")
                        .HasColumnType("integer")
                        .HasColumnName("punto_montado");

                    b.Property<int>("TipoVisita")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_visita");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VisitaIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("visita_id_externo");

                    b.HasKey("Id")
                        .HasName("pk_staging_celero_visitas");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_staging_celero_visitas_hash");

                    b.ToTable("staging_celero_visitas", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Staging.StagingIntratimeFichaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrada");

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_sincronizacion");

                    b.Property<string>("FichajeIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fichaje_id_externo");

                    b.Property<bool>("FlagProcesado")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_procesado");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("salida");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staging_intratime_fichajes");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_staging_intratime_fichajes_hash");

                    b.ToTable("staging_intratime_fichajes", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Staging.StagingPayHawkGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("ErrorProcesamiento")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_procesamiento");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaUltimaSincronizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_sincronizacion");

                    b.Property<bool>("FlagProcesado")
                        .HasColumnType("boolean")
                        .HasColumnName("flag_procesado");

                    b.Property<string>("GastoIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gasto_id_externo");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hash");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("importe");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_staging_pay_hawk_gastos");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_staging_pay_hawk_gastos_hash");

                    b.ToTable("staging_pay_hawk_gastos", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NIF")
                        .IsUnique()
                        .HasDatabaseName("ix_users_nif");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Variable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MapeoValoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mapeo_valores_json");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("QuestionIdExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_id_externo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_variables");

                    b.ToTable("variables", (string)null);
                });

            modelBuilder.Entity("SIG.Domain.Entities.Action", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_clients_client_id");

                    b.HasOne("SIG.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_actions_departments_department_id");

                    b.HasOne("SIG.Domain.Entities.Project", "Project")
                        .WithMany("Actions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_actions_projects_project_id");

                    b.Navigation("Client");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ActionConcept", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Action", "Action")
                        .WithMany("ActionConcepts")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_concepts_actions_action_id");

                    b.HasOne("SIG.Domain.Entities.Concept", "Concept")
                        .WithMany("ActionConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_concepts_concepts_concept_id");

                    b.Navigation("Action");

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ActionUser", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Action", "Action")
                        .WithMany("ActionUsers")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_users_actions_action_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany("ActionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_action_users_users_user_id");

                    b.Navigation("Action");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Approval", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Closure", "Closure")
                        .WithMany("Approvals")
                        .HasForeignKey("ClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_closures_closure_id");

                    b.HasOne("SIG.Domain.Entities.Role", "Role")
                        .WithMany("Approvals")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_roles_role_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_approvals_users_user_id");

                    b.Navigation("Closure");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Closure", "Closure")
                        .WithMany("ApprovalHistory")
                        .HasForeignKey("ClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_approval_history_closures_closure_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approval_history_users_user_id");

                    b.Navigation("Closure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.CalculationLog", b =>
                {
                    b.HasOne("SIG.Domain.Entities.ClosureLine", "ClosureLine")
                        .WithOne("CalculationLog")
                        .HasForeignKey("SIG.Domain.Entities.CalculationLog", "ClosureLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_logs_closure_lines_closure_line_id");

                    b.HasOne("SIG.Domain.Entities.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calculation_logs_concepts_concept_id");

                    b.Navigation("ClosureLine");

                    b.Navigation("Concept");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Closure", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Period", "Period")
                        .WithMany("Closures")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_closures_periods_period_id");

                    b.HasOne("SIG.Domain.Entities.Project", "Project")
                        .WithMany("Closures")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_closures_projects_project_id");

                    b.Navigation("Period");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ClosureLine", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Closure", "Closure")
                        .WithMany("Lines")
                        .HasForeignKey("ClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_closure_lines_closures_closure_id");

                    b.HasOne("SIG.Domain.Entities.Concept", "Concept")
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_closure_lines_concepts_concept_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_closure_lines_users_user_id");

                    b.Navigation("Closure");

                    b.Navigation("Concept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ConceptUser", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Concept", "Concept")
                        .WithMany("ConceptUsers")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concept_users_concepts_concept_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany("ConceptUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_concept_users_users_user_id");

                    b.Navigation("Concept");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Project", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ProjectCostCenter", b =>
                {
                    b.HasOne("SIG.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany("ProjectCostCenters")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_cost_centers_cost_centers_cost_center_id");

                    b.HasOne("SIG.Domain.Entities.Project", "Project")
                        .WithMany("ProjectCostCenters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_cost_centers_projects_project_id");

                    b.Navigation("CostCenter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ProjectUser", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_users_projects_project_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_users_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.User", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SIG.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SIG.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SIG.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Action", b =>
                {
                    b.Navigation("ActionConcepts");

                    b.Navigation("ActionUsers");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Closure", b =>
                {
                    b.Navigation("ApprovalHistory");

                    b.Navigation("Approvals");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SIG.Domain.Entities.ClosureLine", b =>
                {
                    b.Navigation("CalculationLog");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Concept", b =>
                {
                    b.Navigation("ActionConcepts");

                    b.Navigation("ConceptUsers");
                });

            modelBuilder.Entity("SIG.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("ProjectCostCenters");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Period", b =>
                {
                    b.Navigation("Closures");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Project", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Closures");

                    b.Navigation("ProjectCostCenters");

                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("SIG.Domain.Entities.Role", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SIG.Domain.Entities.User", b =>
                {
                    b.Navigation("ActionUsers");

                    b.Navigation("ConceptUsers");

                    b.Navigation("ProjectUsers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
