sonar.projectKey=SIG-es
sonar.projectName=SIG-es Project
sonar.projectVersion=1.0.0
sonar.sources=backend
sonar.tests=backend/SIG.Tests
sonar.exclusions=**/bin/**,**/obj/**,**/*.Tests/**
sonar.test.inclusions=**/SIG.Tests/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/SIG.Tests/**
